apiVersion: apps/v1
kind: Deployment
metadata:
  name: testdeployevents
spec:
  selector:
    matchLabels:
      component: tool
  replicas: 2
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        component: tool
    spec:
      containers:
      - name: envar-demo-container
        image: docker.io/library/nginx:latest

